export type {
  DashboardApiResponse as DashboardResponse,
  DashboardApiAnimal as AnimalDestaque,
  DashboardApiMovement as MovimentacaoRecente,
  DashboardApiQuote as CotacaoBoi,
  DashboardStatus,
  DashboardViewData,
  FeaturedAnimal,
  FinancialChartData,
  FinancialPoint,
  QuickAction,
  RecentMovement,
  SummaryCardData,
  SummaryTrend,
} from '../dashboard.types'
