ALTER TABLE usuario ADD COLUMN sobrenome VARCHAR(150) NOT NULL DEFAULT '';
ALTER TABLE usuario ADD COLUMN telefone VARCHAR(20) NOT NULL DEFAULT '';
ALTER TABLE usuario ADD COLUMN cidade VARCHAR(100) NOT NULL DEFAULT '';
ALTER TABLE usuario ADD COLUMN estado VARCHAR(2) NOT NULL DEFAULT '';
ALTER TABLE usuario ADD COLUMN nome_propriedade_rural VARCHAR(150) NOT NULL DEFAULT '';
